# Generated by Django 4.2.30 on 2026-05-13 17:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Marca')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('TPU', 'TPU'), ('ASA', 'ASA'), ('NYLON', 'Nylon'), ('RESIN', 'Resina'), ('OUTRO', 'Outro')], default='PLA', max_length=20, verbose_name='Material')),
                ('peso_total_g', models.DecimalField(decimal_places=2, help_text='Peso total do carretel em gramas (ex: 1000g = 1kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso total (g)')),
                ('peso_disponivel_g', models.DecimalField(decimal_places=2, help_text='Peso atual disponível. Preenchido automaticamente na criação.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso disponível (g)')),
                ('preco_por_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço por kg (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Fornecedor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filamento',
                'verbose_name_plural': 'Filamentos',
                'ordering': ['material', 'cor'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('peso_filamento_g', models.DecimalField(decimal_places=2, help_text='Gramas de filamento consumidos por peça impressa', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso filamento/unidade (g)')),
                ('comprimento_filamento_m', models.DecimalField(decimal_places=2, help_text='Metros de filamento consumidos por peça', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comprimento filamento/unidade (m)')),
                ('tempo_impressao_horas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tempo de impressão (h)')),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Custo total de produção (filamento + energia + outros)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço de custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de venda (R$)')),
                ('estoque_quantidade', models.IntegerField(default=0, help_text='Quantidade de unidades em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.filamento', verbose_name='Filamento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
