# Generated by Django 4.2.30 on 2026-05-14 17:20

from django.db import migrations, models


def gerar_skus_existentes(apps, schema_editor):
    """Preenche o SKU de todos os produtos já cadastrados antes do unique constraint."""
    Produto = apps.get_model('estoque', 'Produto')
    for p in Produto.objects.order_by('pk'):
        p.sku = f'3D-{p.pk:05d}'
        p.save(update_fields=['sku'])


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        # 1. Adiciona o campo sem unique constraint
        migrations.AddField(
            model_name="produto",
            name="sku",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Gerado automaticamente no cadastro. Ex.: 3D-00001",
                max_length=20,
                verbose_name="SKU",
            ),
        ),
        # 2. Popula SKUs dos registros existentes
        migrations.RunPython(gerar_skus_existentes, migrations.RunPython.noop),
        # 3. Adiciona unique constraint depois dos dados serem únicos
        migrations.AlterField(
            model_name="produto",
            name="sku",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Gerado automaticamente no cadastro. Ex.: 3D-00001",
                max_length=20,
                unique=True,
                verbose_name="SKU",
            ),
        ),
    ]

