# Generated by Django 4.2.30 on 2026-05-19 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data/hora"
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIADO", "Criado"),
                            ("ATUALIZADO", "Atualizado"),
                            ("EXCLUIDO", "Excluído"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Modelo"
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(max_length=50, verbose_name="ID do objeto"),
                ),
                ("objeto_repr", models.TextField(verbose_name="Representação")),
                (
                    "usuario_nome",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Usuário / Origem"
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Manual"),
                            ("ML", "MercadoLivre"),
                            ("SHOPEE", "Shopee"),
                            ("TIKTOK", "TikTok Shop"),
                        ],
                        max_length=20,
                        verbose_name="Plataforma",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Alterações"
                    ),
                ),
                (
                    "event_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON do evento"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["modelo", "objeto_id"],
                        name="auditoria_a_modelo_3fe6d8_idx",
                    )
                ],
            },
        ),
    ]
