# Generated by Django 4.2.30 on 2026-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("ML", "MercadoLivre"),
                            ("SHOPEE", "Shopee"),
                            ("TIKTOK", "TikTok Shop"),
                        ],
                        default="ML",
                        max_length=20,
                        verbose_name="Plataforma",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex.: Minha loja no ML",
                        max_length=100,
                        verbose_name="Nome / Apelido",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=200, verbose_name="App ID (Client ID)"),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="Mantido de forma confidencial — não compartilhe.",
                        max_length=200,
                        verbose_name="Client Secret",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, verbose_name="Access Token"),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, verbose_name="Refresh Token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token expira em"
                    ),
                ),
                (
                    "ml_user_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Seller ID (ML)"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Integração",
                "verbose_name_plural": "Integrações",
                "ordering": ["plataforma", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ProdutoIntegracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku_externo",
                    models.CharField(
                        blank=True,
                        help_text="Preenchido automaticamente após publicação.",
                        max_length=100,
                        verbose_name="ID externo (ex: MLB123456)",
                    ),
                ),
                (
                    "categoria_ml",
                    models.CharField(
                        blank=True,
                        help_text="ID da categoria no MercadoLivre. Obrigatório para publicar.",
                        max_length=50,
                        verbose_name="Categoria ML (ex: MLB3530)",
                    ),
                ),
                (
                    "status_externo",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("closed", "Encerrado"),
                            ("error", "Erro"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status na plataforma",
                    ),
                ),
                (
                    "sincronizado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sincronizado em"
                    ),
                ),
                (
                    "integracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produto_integracoes",
                        to="integracoes.integracao",
                        verbose_name="Integração",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integracoes",
                        to="estoque.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto na Integração",
                "verbose_name_plural": "Produtos nas Integrações",
                "unique_together": {("produto", "integracao")},
            },
        ),
    ]
