# Generated by Django 4.2.30 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtointegracao",
            name="ml_attributes_json",
            field=models.TextField(
                blank=True,
                help_text="Preenchido automaticamente pelo formulário de publicação.",
                verbose_name="Atributos ML (JSON interno)",
            ),
        ),
        migrations.AddField(
            model_name="produtointegracao",
            name="picture_urls",
            field=models.TextField(
                blank=True,
                help_text="Informe ao menos 1 URL de foto pública. Obrigatório para anúncios Clássico.",
                verbose_name="URLs das fotos (1 por linha)",
            ),
        ),
    ]
