# Generated by Django 4.2.30 on 2026-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes", "0002_produtointegracao_pictures_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="integracao",
            name="needs_reauth",
            field=models.BooleanField(
                default=False,
                help_text="Marcado automaticamente quando o token expira e não pode ser renovado.",
                verbose_name="Reautorização necessária",
            ),
        ),
    ]
