# Generated by Django 4.2.30 on 2026-05-19 01:01

from django.db import migrations, models
import django.db.models.deletion
import integracoes.models


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes", "0003_integracao_needs_reauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagemProdutoIntegracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=integracoes.models._imagem_upload_path,
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "is_capa",
                    models.BooleanField(default=False, verbose_name="Capa (1ª foto)"),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto_integracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="integracoes.produtointegracao",
                        verbose_name="Produto-Integração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem de Anúncio",
                "verbose_name_plural": "Imagens de Anúncio",
                "ordering": ["ordem", "criado_em"],
            },
        ),
    ]
