# Generated by Django 4.2.30 on 2026-05-13 17:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('VENDA', 'Venda'), ('FILAMENTO', 'Compra de Filamento'), ('EQUIPAMENTO', 'Equipamento'), ('MANUTENCAO', 'Manutenção'), ('ENERGIA', 'Energia Elétrica'), ('OUTROS_CUSTO', 'Outros Custos'), ('OUTROS_RECEITA', 'Outras Receitas')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_caixa', to='vendas.venda', verbose_name='Venda origem')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
